accounts/urls.py
from django.urls import path
from accounts import views

app_name = "account"

urlpatterns = [
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("account/", views.account, name="account"),
    path("kyc-review/", views.kyc_under_review, name="kyc_under_review"),
    path("notification/", views.notification, name="notification"),
    path("market/", views.market, name="market"),
    path("profile/", views.profile, name="profile"),


]

core/urls.py
from django.urls import path
from core import views, transfer, transaction, payment_request, credit_card, goal, loan


app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),

    # Transfers
    path("search-account/", transfer.search_user_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.ammount_to_transfer, name="amount-transfer"),

    # this guy will process the transfer and check if its valid, if its valid, then you will move to the next page
    path("amount-transfer-process/<account_number>/", transfer.amount_tranfer_process, name="amount-transfer-process"),

    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    # Cancel Transger
    path('transfer-cancel/<account_number>/<transaction_id>/', transfer.transfer_cancel, name="transfer-cancel"), 

    # Recipient - 
    path("my-recipients/", transfer.my_recipients, name="my-recipient"),
    path('recipients/delete/<int:pk>/', transfer.delete_recipient, name='delete_recipient'),


    # # transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),

    # # Payment Request
    path("request-search-account/", payment_request.search_user_request, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-proccess/<account_number>/", payment_request.amount_request_process, name="amount-request-proccess"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.amount_request_final_process, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.request_completed, name="amount-request-completed"),


    # # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settle_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),


    # # Credit Card URLS
    path("my-cards/", credit_card.all_cards, name="credit_cards"),
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),


    # Goal
    path("my-goals/", goal.my_goals, name="goal"),
    path("my-goals-detail/<gid>/", goal.goal_detail, name="goal-detail"),
    path("delete-goal/<gid>/", goal.delete_goal, name="delete-goal"),
    path("fund-goal/<gid>/", goal.fund_goal, name="fund-goal"),
    
    
    # Loan
    path("loan/apply/", loan.apply_for_loan, name="apply-loan"),
    path("loan/loan_history/<loan_id>/", loan.loan_detail, name="loan-detail"),
    path("loan/history/", loan.loan_history, name="loan-history"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # used apps
    path('', include("core.urls")),
    path('auth/', include("userauths.urls")),
    path('account/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/credit_card/all-card.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block content %}

    <!-- bottom navbar start -->
    {% include 'home_i/footer_nav.html' %}
    <!-- bottom navbar end -->


    <!-- header start -->
    <header class="section-t-space">
        <div class="custom-container">
            <div class="header-panel">
                <a href="{% url 'account:dashboard' %}" class="back-btn">
                    <i class="icon" data-feather="arrow-left"></i>
                </a>
                <h2>My cards</h2>

                <a href="#add-card" class="back-btn" data-bs-toggle="modal">
                    <i class="icon" data-feather="plus"></i>
                </a>
            </div>
        </div>
    </header>
    <!-- header end -->
    
    {% if credit_card %}
        <!-- cards section starts -->
        <section class="section-b-space">
            <div class="custom-container">
                <ul class="card-list">
                    
                    {% for c in credit_card %}
                        <li class="credit-card-box color1">
                            
                            <div class="card-logo">
                                <img class="img-fluid logo" src="{% static 'assets/images/logo/logo.png' %}" alt="logo" width="50" />
                                <div class="dropdown">
                                    <ul class="" style="color: #fff; font-weight: 600;">
                                        <li><a class="dropdown-item" href="#"><b>{{c.card_type|title}} Card</b></a></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <h5 class="card-number"><b>{{c.number}}</b></h5>
                                    <h5 class="card-name">{{c.user.kyc.full_name|title}}</h5>
                                </div>
                                <img class="img-fluid chip" src="{% static 'assets/images/svg/card-chip.svg' %}" alt="card-chip" />
                            </div>

                            <div class="d-flex justify-content-between">
                                <h2 class="card-amount">${{c.amount}}</h2>
                                <div class="card-date w-100">
                                    <h6>Exp. Date</h6>
                                    <h6 class="text-white fw-semibold mt-1">{{c.month}}/{{c.year}}</h6>
                                </div>
                                <div class="card-numbers w-100">
                                    <h6 class="cvv-code">Cvv</h6>
                                    <h6 class="text-white fw-semibold mt-1">{{c.cvv}}</h6>
                                </div>
                            </div>
                            <a href="{% url 'core:card-detail' c.card_id %}"> 
                                <p class="text-center mt-1 text-decoration-none text-muted"><span style="color: rgb(190, 190, 190);">Click me to see Card Details</span></p> 
                            </a>
                            
                        </li> 

                    {% endfor %}
                        
                    

                </ul>
            </div>
        </section>
        <!-- cards section end -->
    {% else %}
        <!-- pay-successfully section starts -->
        <section class="section-b-space">
            <div class="custom-container">
                <div class="empty-page">
                    <img
                        class="notification-img"
                        class="img-fluid"
                        src="{% static 'assets/images/svg/notification.svg' %}"
                        alt="notification"
                    />
                    <h3 class="d-block fw-normal dark-text text-center mt-3">
                        You don't have any transaction card for now.
                    </h3>
                    <a href="#add-card" class="btn theme-btn successfully w-100" data-bs-toggle="modal"> Create One </a>
                </div>
            </div>
        </section>
        <!-- pay-successfully section end -->     
    {% endif %}
        
    


    <!-- add card modal starts -->
    <div class="modal add-money-modal fade" id="add-card" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" class="modal-content">
                {% csrf_token %}

                <div class="modal-header">
                    <h2 class="modal-title">Add New Card</h2>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputcard" class="form-label mb-2">Card type</label>
                        <div class="d-flex gap-2">
                            {{card_form.card_type}}
                        </div>
                    </div>

                    <button type="submit" class="btn theme-btn successfully w-100">Add Card</button>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- add card modal end -->


{% endblock content %}




    <!--successful delate card modal start -->
    <div class="modal error-modal fade" id="done-delate" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Successfully Delete</h2>
                </div>
                <div class="modal-body">
                    <div class="error-img">
                        <img class="img-fluid" src="{% static 'assets/images/svg/delate.svg' %}" alt="delate" />
                    </div>
                    <h3>Are you sure you want to delete this card ?</h3>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </div>
        </div>
    </div>
    <!-- successful delate card modal end -->

templates/credit_card/card-detail.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% load humanize %}

{% block content %}

    <!-- header start -->
    <header class="section-t-space">
        <div class="custom-container">
            <div class="header-panel">
                <a href="{{ request.META.HTTP_REFERER|default:'account:dashboard' }}" class="back-btn">
                    <i class="icon" data-feather="arrow-left"></i>
                </a>
                <h2>My cards</h2>

                <!-- <a href="#add-card" class="back-btn" data-bs-toggle="modal">
                    <i class="icon" data-feather="plus"></i>
                </a> -->
            </div>
        </div>
    </header>
    <!-- header end -->

    <!-- cards section starts -->
    <section class="section-b-space">
        <div class="custom-container">
            <ul class="card-list">
                
                <li class="credit-card-box color1">
                    <div class="card-logo">
                        <img class="img-fluid logo" src="{% static 'assets/images/logo/logo.png' %}" alt="logo" width="50" />

                        <div class="dropdown">

                            <ul class="" style="color: #fff; font-weight: 600;">
                                <li><a class="dropdown-item" href="#"><b>{{credit_card.card_type|title}} Card</b></a></li>
                            </ul>
                        </div>
                        
                        <div class="dropdown">
                            <a href="#" class="back-btn" role="button" data-bs-toggle="dropdown">
                                <i class="icon" data-feather="more-horizontal"></i>
                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#edit-card" data-bs-toggle="modal">Add Funds</a></li>
                                <li><a class="dropdown-item" href="#add-money" class="add-money theme-color" data-bs-toggle="modal">Withdraw Funds</a></li>
                                <li><a class="dropdown-item" href="{% url 'core:delete_card' credit_card.card_id %}">Delete Card</a></li>

                            </ul>
                        </div>

                    </div>
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <h5 class="card-number"><b>{{credit_card.number}}</b></h5>
                            <h5 class="card-name">{{credit_card.user.kyc.full_name|title}}</h5>
                        </div>
                        <img class="img-fluid chip" src="{% static 'assets/images/svg/card-chip.svg' %}" alt="card-chip" />
                    </div>
                    <div class="d-flex justify-content-between">
                        <h2 class="card-amount">${{credit_card.amount}}</h2>
                        <div class="card-date w-100">
                            <h6>Exp. Date</h6>
                            <h6 class="text-white fw-semibold mt-1">{{credit_card.month}}/{{credit_card.year}}</h6>
                        </div>
                        <div class="card-numbers w-100">
                            <h6 class="cvv-code">Cvv</h6>
                            <h6 class="text-white fw-semibold mt-1">{{credit_card.cvv}}</h6>
                        </div>
                    </div>
                </li> 

            </ul>
        </div>
    </section>
    <!-- cards section end -->

    <!-- edit card modal starts -->
    <div class="modal add-money-modal fade" id="edit-card" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <form action="{% url 'core:fund-credit-card' credit_card.card_id %}" method="POST" class="modal-content">
                {% csrf_token %}

                <div class="modal-header">
                    <h2 class="modal-title">Add Funds to your ({{credit_card.card_type}}) Card</h2>
                </div>
                <div class="modal-body">
                   
                    <div class="form-group">
                        <label for="inputcardnumber" class="form-label">Card Holder Name</label>
                        <div class="form-input">
                            <input
                                type="text"
                                class="form-control"
                                value="{{credit_card.user.kyc.full_name}}"
                                readonly
                            />
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <label for="inputcardnumber" class="form-label">Account Balance</label>
                        <div class="form-input">
                            <input
                                type="text"
                                class="form-control"
                                value="${{account.account_balance|intcomma}}"
                                readonly
                            />
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <label for="inputcardnumber" class="form-label">Card Number</label>
                        <div class="form-input">
                            <input
                                type="text"
                                class="form-control"
                                value="{{credit_card.number}}"
                                readonly
                            />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputcardnumber" class="form-label">Amount to Fund</label>
                        <div class="form-input">
                            <input
                                type="number"
                                name="funding_amount"
                                class="form-control"
                                placeholder="$0.00"
                            />
                        </div>
                    </div>
                   
                  

                    <button type="submit" class="btn theme-btn successfully w-100">Confirm Transfer</button>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- edit card modal end -->

    <!-- add money modal start -->
    <div class="modal add-money-modal fade" id="add-money" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" action="{% url 'core:withdraw_fund' credit_card.card_id %}" class="modal-content">
                {% csrf_token %}

                <div class="modal-header">
                    <h2 class="modal-title">Withdraw Money</h2>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputcard" class="form-label mb-2">Card Available Balance</label>
                        <div class="d-flex gap-2">
                            <input type="text" value="${{ credit_card.amount|intcomma }}" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputamount" class="form-label mb-2">Amount</label>
                        <div class="form-input">
                            <input type="number" class="form-control" name="amount" placeholder="$0.00" />
                        </div>
                    </div>
                    <button type="submit" class="btn theme-btn successfully w-100">Deposit</button>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- add money modal end -->

{% endblock content %}