accounts/urls.py
from django.urls import path
from accounts import views

app_name = "account"

urlpatterns = [
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("account/", views.account, name="account"),
    path("kyc-review/", views.kyc_under_review, name="kyc_under_review"),
    path("notification/", views.notification, name="notification"),
    path("market/", views.market, name="market"),
    path("profile/", views.profile, name="profile"),


]

core/urls.py
from django.urls import path
from core import views, transfer, transaction, payment_request, credit_card, goal, loan


app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),

    # Transfers
    path("search-account/", transfer.search_user_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.ammount_to_transfer, name="amount-transfer"),

    # this guy will process the transfer and check if its valid, if its valid, then you will move to the next page
    path("amount-transfer-process/<account_number>/", transfer.amount_tranfer_process, name="amount-transfer-process"),

    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    # Cancel Transger
    path('transfer-cancel/<account_number>/<transaction_id>/', transfer.transfer_cancel, name="transfer-cancel"), 

    # Recipient - 
    path("my-recipients/", transfer.my_recipients, name="my-recipient"),
    path('recipients/delete/<int:pk>/', transfer.delete_recipient, name='delete_recipient'),


    # # transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),

    # # Payment Request
    path("request-search-account/", payment_request.search_user_request, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-proccess/<account_number>/", payment_request.amount_request_process, name="amount-request-proccess"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.amount_request_final_process, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.request_completed, name="amount-request-completed"),


    # # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settle_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),


    # # Credit Card URLS
    path("my-cards/", credit_card.all_cards, name="credit_cards"),
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),


    # Goal
    path("my-goals/", goal.my_goals, name="goal"),
    path("my-goals-detail/<gid>/", goal.goal_detail, name="goal-detail"),
    path("delete-goal/<gid>/", goal.delete_goal, name="delete-goal"),
    path("fund-goal/<gid>/", goal.fund_goal, name="fund-goal"),
    
    
    # Loan
    path("loan/apply/", loan.apply_for_loan, name="apply-loan"),
    path("loan/loan_history/<loan_id>/", loan.loan_detail, name="loan-detail"),
    path("loan/history/", loan.loan_history, name="loan-history"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # used apps
    path('', include("core.urls")),
    path('auth/', include("userauths.urls")),
    path('account/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("register/", views.register_view, name="register"),    
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),

    # # path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("forget_password/", views.forget_password, name="forget_password"),
    path("reset_validate/<uidb64>/<token>/", views.reset_validate, name="reset_validate"),
    path("reset_password/", views.reset_password, name="reset_password"),

    path("created/", views.account_created, name="account_created"),

    
    

]

templates/home_i/balance_area.html
{% load static %}
{% load humanize %}

    <section class="section-b-space">
        <div class="custom-container">
            <div class="card-box">
                <div class="card-details">
                    <div class="d-flex justify-content-between">
                        <h5 class="fw-semibold">Total Balance</h5>
                        <img src="{% static 'assets/images/svg/ellipse.svg' %}" alt="ellipse" />
                    </div>

                    <div class="d-flex">
                        <h1 class="mt-2 text-white">
                            <span id="balance-text">${{account.account_balance|intcomma}}</span>
                            <img id="toggle-balance" 
                                src="{% static 'assets/images/eye.png' %}" 
                                style="width: 20px; margin-left: 2px; cursor: pointer; margin-top: -5px;" />
                        </h1>
                    </div>

                    <div class="amount-details">
                        <div class="amount w-50 text-start">
                            <div class="d-flex align-items-center justify-content-start">
                                <!-- <img class="img-fluid icon" src="{% static 'assets/images/svg/arrow-down-right.svg' %}" alt="down" /> -->
                                <h5>Hi</h5>
                            </div>
                            <h3 class="text-white" style="font-size: 12px;">{{user.kyc.full_name|title|default:'Complete KYC'}}</h3>
                        </div>
                        <div class="amount w-50 text-end border-0">
                            <div class="d-flex align-items-center justify-content-end">
                                <img class="img-fluid icon" src="{% static 'assets/images/svg/arrow-down-right.svg' %}" alt="up" />
                                <h5>Last Received</h5>
                            </div>
                            
                            {% if recent_recieved_transfer %}
                                {% for recent_recieved_transfer in recent_recieved_transfer %}

                                    <h3 class="text-white">$ {{recent_recieved_transfer.amount|intcomma}}</h3>
                                    
                                {% endfor %}
                            {% else %}
                                <h3 class="text-white">$0.00</h3>
                            {% endif %}
                                
                            
                                
                        </div>
                    </div>
                </div>
                <a href="{% url 'core:request-search-account' %}" class="add-money theme-color">+ Add Money </a>
            </div>
        </div>
    </section>

    
    <!-- categories section starts -->
    <section class="categories-section section-b-space">
        <div class="custom-container">
            <ul class="categories-list">
                <li>
                    <a href="{% url 'core:search-account' %}">
                        <div class="categories-box">
                            <i class="categories-icon" data-feather="repeat"></i>
                        </div>
                        <h5 class="mt-2 text-center">Transfer</h5>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:transactions' %}">
                        <div class="categories-box">
                            <i class="categories-icon" data-feather="file-text"></i>
                        </div>
                        <h5 class="mt-2 text-center">History</h5>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:request-search-account' %}">
                        <div class="categories-box">
                            <i class="categories-icon icon1" data-feather="log-in"></i>
                        </div>
                        <h5 class="mt-2 text-center">Request</h5>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:goal' %}">
                        <div class="categories-box">
                            <i class="fa fa-bank" style="font-size:23px;color:rgb(115, 0, 255)"></i>
                        </div>
                        <h5 class="mt-2 text-center">Goals</h5>
                    </a>
                </li>
            </ul>
        </div>
    </section>
    <!-- categories section end -->

    <script>
        document.addEventListener("DOMContentLoaded", function () {

            const balanceText = document.getElementById("balance-text");
            const toggleBtn = document.getElementById("toggle-balance");

            let realBalance = balanceText.textContent;
            let hidden = false;

            toggleBtn.addEventListener("click", () => {
                if (!hidden) {
                    balanceText.textContent = "******";
                    toggleBtn.src = "{% static 'assets/images/eye-off.webp' %}";
                } else {
                    balanceText.textContent = realBalance;
                    toggleBtn.src = "{% static 'assets/images/eye.png' %}";
                }
                hidden = !hidden;
            });

        });
    </script>

templates/home_i/footer_nav.html
{% load static %}

<div class="navbar-menu">
               
    <div class="navbar-menu elements-navbar position-relative">

        <div class="scanner-bg">
            <a href="{% url 'account:market' %}" class="scanner-btn">
                <!-- <img class="unactive" src="{% static 'assets/images/svg/bar-chart.svg' %}" alt="bag"> -->
                <!-- <img class="active" src="{% static 'assets/images/svg/bar-chart-fill.svg' %}" alt="bag"> -->
                <i class="fa fa-wifi" style="font-size:30px;color:rgb(255, 255, 255)"></i>
            </a>
        </div>

        <ul>
            <li class="active">
                <a href="{% url 'account:dashboard' %}">
                    <div class="icon">
                        <img class="unactive" src="{% static 'assets/images/svg/mpay.svg' %}" alt="mPay">
                        <img class="" src="{% static 'assets/images/svg/mpay-fill.svg' %}" alt="mPay">
                    </div>
                    <h5 class="active">mPay</h5>
                </a>
            </li>

            <li>
                <a href="{% url 'core:goal' %}">
                    <div class="icon">
                        <!-- <i class="sidebar-icon" data-feather="file-text"></i>                         -->
                        <i class="fa fa-bank" style="font-size:18px;color:rgb(201, 201, 201)"></i>
                    </div>
                    <h5 class="mt-1"> Goals</h5>
                </a>
            </li>

            <li></li>

            <li>
                <a href="{% url 'core:credit_cards' %}">
                    <div class="icon">
                        <!-- <img class="unactive" src="{% static 'assets/images/svg/bar-chart.svg' %}" alt="bag">
                        <img class="active" src="{% static 'assets/images/svg/bar-chart-fill.svg' %}" alt="bag"> -->
                        <i class="service-icon" data-feather="credit-card"></i>
                    </div>
                    <h5>Cards</h5>
                </a>
            </li>

            <li>
                <a href="{% url 'account:profile' %}">
                    <div class="icon">
                        <img class="unactive" src="{% static 'assets/images/svg/user.svg' %}" alt="profile">
                        <img class="active" src="{% static 'assets/images/svg/user-fill.svg' %}" alt="profile">
                    </div>
                    <h5>Profile</h5>
                </a>
            </li>
        </ul>
    </div>
    
</div>

templates/home_i/header.html
{% load static %}

<header class="section-t-space">
    <div class="custom-container">
        <div class="header-panel">
            <a class="sidebar-btn" data-bs-toggle="offcanvas" data-bs-target="#offcanvasLeft">
                <i class="menu-icon" data-feather="menu"></i>
            </a>
            <img class="img-fluid logo" src="{% static 'assets/images/logo/logo.png' %}" alt="logo" />

            <a href="{% url 'account:notification' %}" class="notification">
                <i class="notification-icon" data-feather="bell"></i>
            </a>
        </div>
    </div>
</header>
    
    

templates/home_i/monthly_statistics.html
{% load static %}
    <section>
        <div class="custom-container">
            <div class="statistics-banner">
                <div class="d-flex justify-content-center gap-3">
                    <div class="statistics-image">
                        <i class="icon" data-feather="bar-chart-2"></i>
                    </div>
                    <div class="statistics-content d-block">
                        <h5>Monthly Statistics</h5>
                        <h6>30% better performance than previous</h6>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/home_i/services.html
{% load static %} 

<!-- quick send section starts -->
<section class="">
    <div class="custom-container">
        <div class="title">
            <h2>Quick send to</h2>
            <a href="{% url 'core:my-recipient' %}">See all</a>
        </div>
    </div>

    <div class="quick-send" style="margin-left: 15px;">

        <div class="profile">
            <a href="{% url 'core:search-account' %}" class="profile new-profile">
                <div class="new-image">
                    <i class="icon" data-feather="plus"></i>
                </div>
            </a>
        </div>

        {% for r in recipients  %}

            <div class="profile">
                <a href="{% url 'core:amount-transfer' r.account.account_number  %}">

                    {% if r.recipient_user.kyc.image %}
                        <img class="img-fluid " src="{{r.recipient_user.kyc.image.url}}" width="40" alt="ava" style="border-radius: 40%;" />

                    {% else %}
                        <img class="img-fluid " src="{% static 'assets/avatar.png' %}" width="50" alt="ava" style="border-radius: 50%;" />
                        
                    {% endif %}   
                    <h5 style="margin-left: -20px;">{{r.recipient_user.kyc.full_name|truncatechars:5|title|default:'No KYC'}}</h5>
                </a>
            </div>

        {% empty %}

            <p style="align-content: center;">You don't have any recipients yet.</p>
            
        {% endfor %}

    </div>
</section>
<!-- quick send section end -->

templates/home_i/sidebar.html
{% load static %} 
{% load humanize %}

    <div class="offcanvas-header sidebar-header">
        <div class="sidebar-logo">
            <img class="img-fluid logo" src="{% static 'assets/images/logo/logo.png' %}" alt="logo" />
        </div>
        <div class="balance">
            <img class="img-fluid balance-bg" src="{% static 'assets/images/background/auth-bg.jpg' %}" alt="auth-bg" />
            <h5>Balance</h5>
            <h2>${{account.account_balance|intcomma}}</h2>
        </div>
    </div>

    <div class="offcanvas-body">
        <div class="sidebar-content">
            <ul class="link-section">
                <li>
                    <a href="{% url 'account:dashboard' %}" class="pages">
                        <i class="sidebar-icon" data-feather="command"></i>
                        <h3>Dashboard</h3>
                    </a>
                </li>

                <li>
                    <a href="{% url 'account:account' %}" class="pages">
                        <i class="sidebar-icon" data-feather="user"></i>
                        <h3>Account</h3>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:credit_cards' %}" class="pages">
                        <i class="sidebar-icon" data-feather="credit-card"></i>
                        <h3>Cards</h3>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:goal' %}" class="pages">
                        <!-- <i class="sidebar-icon" data-feather="file-text"></i> -->
                        <i class="fa fa-bank" style="font-size:20px;color:rgb(23, 23, 23)"></i>
                        <h3>Goals</h3>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:loan-history' %}" class="pages">
                        <!-- <i class="sidebar-icon" data-feather="file-text"></i> -->
                        <i class="fa fa-cubes" style="font-size:20px;color:rgb(23, 23, 23)"></i>
                        <h3>Loan</h3>
                    </a>
                </li>
                
                <li>
                    <a href="{% url 'userauths:logout' %}" class="pages">
                        <i class="sidebar-icon" data-feather="log-out"></i>
                        <h3>Log out</h3>
                    </a>
                </li>

            </ul>

            <div class="mode-switch">
                <ul class="switch-section">
                    <li>
                        <h3>Dark</h3>
                        <div class="switch-btn">
                            <input id="dark-switch" type="checkbox" />
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
        

templates/home_i/transactions.html
{% load static %}
{% load humanize %}


 
<section class="section-b-space" style="margin-bottom: -20px;">
    <div class="custom-container">
        <div class="title">
            <h2>Transaction</h2>
            <!-- <img class="img-fluid icon" src="{% static 'assets/images/svg/arrow-down-right.svg' %}" alt="down" /> -->
            <a href="{% url 'core:transactions' %}">See all</a>
        </div>
        
        <div class=" ">
            
            {% if all_transactions %}
                {% for t in all_transactions %}
                    <!-- ==========================================================
                    LOOPING THROUGH ALL TRANSACTIONS
                    "t" = a single transaction object from all_transactions
                ========================================================== -->
                    <div class="p-2 mb-2" style="border: 1px solid rgb(210, 207, 207); border-radius: 5px;">
                        <!-- Link to open the full transaction detail page -->
                        <a href="{% url 'core:transaction-detail' t.transaction_id %}" class="transaction-main-link">

                            <!-- ===========================
                                This Guy will check and give me the name of the receiver or sender based on the transaction
                            =========================== -->
                            <div>
                                <h5 class="fw-semibold dark-text">
                                    {% if t.transaction_type == "transfer" %}
                                    <!-- ------------------------------
                                        CASE 1: A Transfer Transaction
                                    ------------------------------ -->
                                        {% if t.sender == request.user %}
                                        <!-- User SENT money to someone -->
                                        Transfer to ({{ t.reciever.kyc.full_name|default:'No KYC'|title }})
                                        {% else %}
                                        <!-- User RECEIVED money -->
                                        Transfer from ({{ t.sender.kyc.full_name|default:'No KYC'|title }})
                                        {% endif %}

                                    {% elif t.transaction_type == "request" %}
                                    <!-- ------------------------------
                                        CASE 2: A Money Request
                                    ------------------------------ -->
                                        {% if t.sender == request.user %}
                                        <!-- User SENT a money request -->
                                        Request sent to ({{ t.reciever.kyc.full_name|default:'No KYC'|title }})
                                        {% else %}
                                        <!-- User RECEIVED a money request -->
                                        Request from ({{ t.sender.kyc.full_name|default:'No KYC'|title }})
                                        {% endif %}
                                    {% endif %}
                                </h5>

                                <div class="transaction-meta">
                                    <!-- ===================================
                                        This Guy will check and give me the transaction type
                                    =================================== -->
                                    <h6 class="fw-normal light-text mt-1">
                                        {% if t.sender == request.user and t.transaction_type == "transfer" %}
                                        <!-- User SENT money = Debit -->
                                            <span class="text-danger">Transfer | Debit</span>

                                        {% elif t.reciever == request.user and t.transaction_type == "transfer" %}
                                        <!-- User RECEIVED money -->
                                            <span class="text-success">Transfer | Received</span>

                                        {% elif t.transaction_type == "request" %}
                                        <!-- Money request -->
                                            <span class="text-info">Request</span>
                                        {% endif %}
                                    </h6>

                                    <!-- ===================================
                                        DATE AND TIME OF TRANSACTION
                                        E.g. "04:22 | 12 Feb, 2025"
                                    =================================== -->
                                    <h6 class="time fw-normal light-text mt-1">
                                        <small>{{ t.date|date:"h:i" }}</small> | {{ t.date|date:"d M, Y" }}
                                    </h6>
                                </div>
                            </div>

                            

                            <!-- ===========================
                                BOTTOM SECTION:
                                - Status
                                - Amount
                                - Request Actions (Settle/Delete)
                            =========================== -->
                            <div class="mt-3">
                                <div class="transaction-status-amount">
                                    <!-- ==========================
                                        This Guy will check and give me the transaction status
                                    ========================== -->
                                    {% if t.status == 'completed' %}
                                        <p class="fw-semibold text-success">{{ t.status|title }}</p>

                                    {% elif t.status == 'processing' or t.status == 'request_processing' %}
                                        <p class="fw-semibold text-warning">{{ t.status|title }}</p>

                                    {% elif t.status == 'failed' %}
                                        <p class="fw-semibold text-danger">{{ t.status|title }}</p>

                                    {% elif t.status == 'request_sent' %}
                                        <p class="fw-semibold text-primary">Request Sent</p>

                                    {% elif t.status == 'request_settled' %}
                                        <p class="fw-semibold text-success">Settled </p>
                                    {% endif %}

                                    <!-- ==========================
                                        AMOUNT (formatted with comma)
                                    ========================== -->
                                    <span class="dark-text amount-display">
                                        ${{ t.amount|intcomma }}
                                    </span>
                                </div>

                                <!-- ======================================
                                    EXTRA ACTION BUTTONS FOR REQUESTS ONLY
                                    - If user sent the request → View/Delete
                                    - If user received the request → Settle/View
                                ====================================== -->
                                {% if t.transaction_type == "request" %}
                                    <div class="request-actions">
                                        <ul class="element-list">

                                            {% if t.sender == request.user %}
                                                <!-- User SENT the request -->
                                                {% if t.status == 'request_sent' %}

                                                    <li>
                                                        <a href="{% url 'core:transaction-detail' t.transaction_id %}" class="btn theme-btn  p-1 btn-sm">View Request</a>
                                                        <a href="{% url 'core:delete-request' t.sender.account.account_number t.transaction_id %}" class="btn gray-btn  p-1 btn-sm">Delete Request</a>                                                    
                                                    </li> 
                                                {% endif %}

                                            {% else %}
                                                <!-- User RECEIVED the request -->
                                                {% if t.status == 'request_sent' %}
                                                        <li>
                                                            <a href="{% url 'core:settlement-confirmation' t.sender.account.account_number t.transaction_id %}" class="btn theme-btn  p-1 btn-sm">Settle</a>
                                                            <a href="{% url 'core:transaction-detail' t.transaction_id %}" class="btn gray-btn  p-1 btn-sm">View Request</a>                                                    
                                                        </li>
            
                                                {% endif %}
                                            {% endif %}

                                        </ul>

                                    </div>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                {% endfor %}
            
            {% else %}
                    <p>You don't have any transaction history.</p>
            {% endif %}
                

            

        </div>
    </div>
</section>