core/urls.py
from django.urls import path
from core import views, transfer, transaction, payment_request, credit_card, goal, loan


app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),

    # Transfers
    path("search-account/", transfer.search_user_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.ammount_to_transfer, name="amount-transfer"),

    # this guy will process the transfer and check if its valid, if its valid, then you will move to the next page
    path("amount-transfer-process/<account_number>/", transfer.amount_tranfer_process, name="amount-transfer-process"),

    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    # Cancel Transger
    path('transfer-cancel/<account_number>/<transaction_id>/', transfer.transfer_cancel, name="transfer-cancel"), 

    # Recipient - 
    path("my-recipients/", transfer.my_recipients, name="my-recipient"),
    path('recipients/delete/<int:pk>/', transfer.delete_recipient, name='delete_recipient'),


    # # transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),

    # # Payment Request
    path("request-search-account/", payment_request.search_user_request, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-proccess/<account_number>/", payment_request.amount_request_process, name="amount-request-proccess"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.amount_request_final_process, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.request_completed, name="amount-request-completed"),


    # # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settle_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),


    # # Credit Card URLS
    path("my-cards/", credit_card.all_cards, name="credit_cards"),
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),


    # Goal
    path("my-goals/", goal.my_goals, name="goal"),
    path("my-goals-detail/<gid>/", goal.goal_detail, name="goal-detail"),
    path("delete-goal/<gid>/", goal.delete_goal, name="delete-goal"),
    path("fund-goal/<gid>/", goal.fund_goal, name="fund-goal"),
    
    
    # Loan
    path("loan/apply/", loan.apply_for_loan, name="apply-loan"),
    path("loan/loan_history/<loan_id>/", loan.loan_detail, name="loan-detail"),
    path("loan/history/", loan.loan_history, name="loan-history"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # used apps
    path('', include("core.urls")),
    path('auth/', include("userauths.urls")),
    path('account/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/goals/goal-detail.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% load humanize %}

{% block content %}

    <!-- bottom navbar start -->
    {% include 'home_i/footer_nav.html' %}
    <!-- bottom navbar end -->

    <!-- header start -->
    <header class="section-t-space">
        <div class="custom-container">
            <div class="header-panel">
                <a href="{{ request.META.HTTP_REFERER|default:'account:dashboard' }}" class="back-btn">
                    <i class="icon" data-feather="arrow-left"></i>
                </a>
                <h2>Goal Details</h2>

                <a href="#add-money" class="back-btn" data-bs-toggle="modal">
                    <i class="icon" data-feather="plus"></i>
                </a>
            </div>
        </div>
    </header>
    <!-- header end -->

    <!-- news-update-details section starts -->
    <section class="section-b-space">
        <div class="custom-container">
            <div class="news-details">
                <img class="img-fluid news-img w-100" src="{{goal.image.url}}" alt="img1" />
                <div class="news-content">
                    <h2>{{goal.title}}</h2>

                    <div style="margin-top: -15px;" class="d-flex justify-content-center gap-4">
                        
                        <a href="{% url 'core:delete-goal' goal.gid %}" class="btn btn-xs btn-danger">Delete Goal</a>
                        
                        {% if goal.is_completed == False %}
                            <button class="btn btn-xs btn-warning" type="button">In Progress {{ goal.progress_percentage|floatformat:2 }}%</button>
                        {% else  %}
                            <button class="btn btn-xs btn-success" type="button">Goal Status: Archieved 🎉 </button>
                        {% endif %}

                        <a href="#add-money" class="btn btn-xs btn-success" data-bs-toggle="modal">
                            <!-- <i class="icon" data-feather="plus"></i> -->
                            + Fund Goal
                        </a>

                            
                    </div>

                    <style>
                    .btn-xs {
                        padding: 0.25rem 0.5rem;
                        font-size: 0.75rem;
                        line-height: 1.2;
                        border-radius: 0.2rem;
                    }
                    </style>

                    <hr>

                    <h5>Date: {{goal.created_at|date:"d M, Y"}} | Dead Line: <span style="color: blueviolet;">{{goal.deadline}}</span></h5>

                    <h5>Target Amount: <span style="color: blueviolet;">${{goal.target_amount}}</span> | Currently: <span style="color: blueviolet;">${{goal.current_amount}}</span></h5>

                    <h5>Goal Type: <span style="color: blueviolet;">{{goal.goal_type}}</span></h5>

                    <div class="news-description">
                        <h5>Goal Description:</h5>
                        <p>{{goal.description}}</p>

                        <div class="investment-banner">
                            <div class="investment-content">
                                <h5>How to earn more cash so you may invest more</h5>
                                <h6>Earn 50% with this investment.</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- news-update-details section end -->

    <!-- add money modal start -->
    <div class="modal add-money-modal fade" id="add-money" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" action="{% url 'core:fund-goal' goal.gid %}" class="modal-content">
                {% csrf_token %}

                <div class="modal-header">
                    <h2 class="modal-title" style=" font-size: 17px;">Add Funds to your <span style="color: blueviolet;">{{ goal.goal_type }}</span> Goal</h2>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputcard" class="form-label mb-2"> Account Balance</label>
                        <div class="d-flex gap-2">
                            <input type="text" value="${{ user.account.account_balance|intcomma }}" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputamount" class="form-label mb-2">Amount</label>
                        <div class="form-input">
                            <input type="number" class="form-control" name="current_amount" placeholder="$0.00" />
                        </div>
                    </div>
                    <button type="submit" class="btn theme-btn successfully w-100">Add</button>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- add money modal end -->

{% endblock content %}

templates/goals/my-goal.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block content %}

    <!-- bottom navbar start -->
    {% include 'home_i/footer_nav.html' %}
    <!-- bottom navbar end -->

    <!-- header start -->
    <header class="section-t-space">
        <div class="custom-container">
            <div class="header-panel">
                <a href="{% url 'account:dashboard' %}" class="back-btn">
                    <i class="icon" data-feather="arrow-left"></i>
                </a>
                <h2> Goals</h2>

                <a href="#add-card" class="back-btn" data-bs-toggle="modal">
                    <i class="icon" data-feather="plus"></i>
                </a>
            </div>
        </div>
    </header>
    <!-- header end -->
    
    <!-- saving plans section starts -->
    <section>
        <div class="custom-container">
            
            <div class="row">
                
                {% for g in goal %}
                    <a href="{% url 'core:goal-detail' g.gid %}" class="col-6 gap-4">
                        <div class="saving-plan-box mb-4">
                            <div class="saving-plan-icon">
                                <img class="img-fluid" src="{{g.image.url|default:''}}" alt="p10" />
                            </div>
                            <h3>{{g.goal_type }}</h3>
                            <h6>Current Saved</h6>
                            <h5 class="theme-color">${{g.current_amount }}</h5>
                            <hr>
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <h5 class="theme-color">Target ${{g.target_amount }}</h5>
                            </div>
                            <h6>Dead Line: &nbsp;{{g.deadline }}</h6>
                        </div>
                    </a>
                
                {% empty %}
                    <!-- pay-successfully section starts -->
                    <section class="section-b-space">
                        <div class="custom-container">
                            <div class="empty-page">
                                <img
                                    class="notification-img"
                                    class="img-fluid"
                                    src="{% static 'assets/images/svg/notification.svg' %}"
                                    alt="notification"
                                />
                                <h3 class="d-block fw-normal dark-text text-center mt-3">
                                    You don't have any Goal for now.
                                </h3>
                                <a href="#add-card" class="btn theme-btn successfully w-100" data-bs-toggle="modal"> Create One </a>
                            </div>
                        </div>
                    </section>
                    <!-- pay-successfully section end -->
                {% endfor %}

            </div>
        </div>
    </section>
    <!-- saving plans section end -->

    <!-- add card modal starts -->
    <div class="modal add-money-modal fade" id="add-card" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" class="modal-content" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="modal-header">
                    <h2 class="modal-title">Add New Goal</h2>
                </div>
                
                <div class="modal-body">
                    
                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Image</label>
                        {{form.image}}
                    </div>

                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Type</label>
                        <div class="form-input mb-3">
                            {{form.goal_type}}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Title</label>
                        {{form.title}}
                    </div>
                    
                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Target Amount</label>
                        {{form.target_amount}}
                    </div>
                    
                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Dead Line</label>
                        {{form.deadline}}
                    </div>
                    
                    <div class="form-group">
                        <label for="inputcards" class="form-label mb-2">Description</label>
                        {{form.description}}
                    </div>

                    <button type="submit" class="btn theme-btn successfully w-100">Add Goal</button>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- add card modal end -->

    <!-- edit card modal starts -->
    <div class="modal add-money-modal fade" id="edit-card" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Edit Card</h2>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputcard" class="form-label mb-2">Card type</label>
                        <div class="d-flex gap-2">
                            <select id="inputcard" class="form-select">
                                <option>Select card type</option>
                                <option>Master Card</option>
                                <option selected="">Visa Card</option>
                                <option>RuPay Card</option>
                                <option>Business Card</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputcardnumber" class="form-label">Card Number</label>
                        <div class="form-input">
                            <input
                                type="text"
                                class="form-control"
                                id="inputcardnumber"
                                value="**** **** **** 2563"
                                placeholder="Enter card number"
                            />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-7">
                            <div class="form-group">
                                <label class="form-label">Exp. Date</label>
                                <div class="form-input mb-3">
                                    <input type="date" value="2024-12-31" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="form-group">
                                <label class="form-label">CVV</label>
                                <div class="form-input mb-3">
                                    <input type="number" class="form-control" placeholder="Enter cvv" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="cards.html" class="btn theme-btn successfully w-100">Edit Card</a>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </div>
        </div>
    </div>
    <!-- edit card modal end -->

    <!-- delate card modal start -->
    <div class="modal error-modal fade" id="delate" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="error-img">
                        <img class="img-fluid" src="assets/images/svg/delate.svg" alt="delate" />
                    </div>
                    <h3>Are you sure you want to delete this card ?</h3>
                    <a href="#done-delate" class="btn theme-btn successfully w-100" data-bs-toggle="modal">Delete card</a>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </div>
        </div>
    </div>
    <!-- delate card modal end -->

    <!--successful delate card modal start -->
    <div class="modal error-modal fade" id="done-delate" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Successfully Delete</h2>
                </div>
                <div class="modal-body">
                    <div class="error-img">
                        <img class="img-fluid" src="assets/images/svg/delate.svg" alt="delate" />
                    </div>
                    <h3>Are you sure you want to delete this card ?</h3>
                </div>
                <button type="button" class="btn close-btn" data-bs-dismiss="modal">
                    <i class="icon" data-feather="x"></i>
                </button>
            </div>
        </div>
    </div>
    <!-- successful delate card modal end -->



{% endblock content %}